matrix:
  include:
  - language: java
    jdk: openjdk9
    script:
      - make test

  - language: java
    jdk: oraclejdk9
    script:
      - make test

  - language: c
    compiler:
      - gcc
      - clang
    before_script:
      - cd src/c
    script:
      - make test